onboarding = false
[theme]
name = "tokyo-night"

[ui.toast]
delivery = "system"

[keys]
prefix = "ctrl+;"
rename_tab = "prefix+shift+t"

[[keys.command]]
key = "ctrl+g"
type = "pane"
command = "lazygit"

[[keys.command]]
key = "prefix+t"
type = "popup"
command = "fish"
width = "90%"
height = "90%"

[keys.indexed]
# quickly switch between workspaces and tabs with numbers
workspaces = "ctrl+shift"
tabs = "ctrl"

[ui]
hide_tab_bar_when_single_tab = true

[ui.sidebar.agents]
rows = [["state_icon", "workspace", "tab"]]

[experimental]
pane_history = false

[ui.sound]
enabled = true
