#!/bin/sh

self=$(realpath "$0")
real_gh=
IFS=:
for directory in $PATH; do
    if [ -x "$directory/gh" ] && [ "$(realpath "$directory/gh")" != "$self" ]; then
        real_gh=$directory/gh
        break
    fi
done
unset IFS
[ -n "$real_gh" ] || { echo 'gh: executable not found' >&2; exit 127; }

if [ -z "${GH_TOKEN-}${GITHUB_TOKEN-}" ] && [ "${1-}" != auth ]; then
    remote=$(git remote get-url --push origin 2>/dev/null)
    case $remote in
        https://?*@github.com/*)
            account=${remote#https://}
            GH_TOKEN=$("$real_gh" auth token --hostname github.com --user "${account%%@*}") || exit 1
            export GH_TOKEN
            ;;
    esac
fi

exec "$real_gh" "$@"
