#!/bin/sh

[ "$1" = get ] || exit 0

while IFS='=' read -r key value; do
    case "$key" in
        host) host=$value ;;
        username) username=$value ;;
    esac
done

case "$host" in
    github.com | gist.github.com) ;;
    *) exit 0 ;;
esac

token=$(gh auth token --hostname github.com ${username:+--user "$username"}) || exit 1
printf 'username=x-access-token\npassword=%s\n\n' "$token"
