cask_args appdir: '/Applications'

brew 'gh'
brew 'fish'
brew 'lsd'
brew 'nvim'
cask 'raycast'
cask 'arc'
cask 'karabiner-elements'
cask 'warp'
cask 'cleanmymac'
cask 'spotify'
cask 'miniconda'
cask 'hiddenbar'
