#!/bin/bash

PLUGIN_DIR="$CONFIG_DIR/plugins"

# --- Colors ---
export TEXT_COLOR=0xffffffff
export BAR_COLOR=0xff000000
export ACCENT_COLOR=0xffffffff

# --- Bar Appearance ---
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
sketchybar --bar \
  position=top \
  height=32 \
  font_smoothing=on \
  color=$BAR_COLOR

# --- Changing Defaults ---
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items
default=(
  icon.font="SF Pro:Medium:12.0"
  label.font="SF Pro:Medium:12.0"
  # label.font="JetBrainsMono Nerd Font Mono:Semibold:10.0"
  icon.color=$ACCENT_COLOR
  label.color=$TEXT_COLOR
  padding_left=10
  padding_right=10
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default[@]}"

# --- Left side ---
sketchybar --add item front_app left \
  --set front_app \
  icon.drawing=off \
  script="$PLUGIN_DIR/front_app.sh" \
  --subscribe front_app front_app_switched

sketchybar --add item media left \
  --set media \
  icon=􀊄 \
  label.max_chars=40 \
  scroll_texts=on \
  script="$PLUGIN_DIR/media.sh" \
  --subscribe media media_change

# --- Right side ---
sketchybar --add item calendar right \
  --set calendar \
  icon=􀧞 \
  update_freq=30 \
  script="$PLUGIN_DIR/calendar.sh"

sketchybar --add item battery right \
  --set battery \
  update_freq=120 \
  script="$PLUGIN_DIR/battery.sh" \
  --subscribe battery system_woke power_source_change

sketchybar --add item volume right \
  --set volume \
  script="$PLUGIN_DIR/volume.sh" \
  --subscribe volume volume_change

sketchybar --add item cpu right \
  --set cpu \
  update_freq=3 \
  icon=􀧓 \
  script="$PLUGIN_DIR/cpu.sh"

sketchybar --add item memory right \
  --set memory \
  update_freq=60 \
  icon=􀫦 \
  script="$PLUGIN_DIR/memory.sh"

sketchybar --add item network right \
  --set network \
  update_freq=5 \
  icon=􀤆 \
  script="$PLUGIN_DIR/network.sh"

# --- Finalizing setup ---
# The below command is only needed at the end of the initial configuration
sketchybar --update
