package:
  name: btk
  version: "0.3"

source:
  git_url: https://github.com/pyomeca/BTKCore.git

build:
  number: 0

requirements:
  build:
    - setuptools
    - python
    - numpy x.x
    - cmake
    - swig

  run:
    - python

about:
  home: https://github.com/pyomeca/BTKCore
  summary: Read, modify, process, and write acquisition data recorded by a motion capture system

extra:
    recipe-maintainers:
        - mrtnz
